version: '3.9'

services:
  web:
    container_name: places_remember
    build: .
    command:  bash -c "python /usr/src/places_remember/manage.py migrate --noinput && 
              python /usr/src/places_remember/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/places_remember
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data: