# Generated by Django 4.1.4 on 2023-02-19 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ymap.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    django_ymap.fields.YmapCoord(
                        max_length=200, verbose_name="Address"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=150, verbose_name="Title"
                    ),
                ),
                ("review", models.CharField(max_length=10000, verbose_name="Remember")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Date of create"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=150,
                        null=True,
                        unique=True,
                        verbose_name="URL",
                    ),
                ),
                (
                    "auth",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
            ],
            options={
                "verbose_name": "place",
                "verbose_name_plural": "places",
                "ordering": ["-created_at"],
            },
        ),
    ]
