# Generated by Django 4.1.4 on 2023-02-26 17:13

import app_remember.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_remember", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="images",
            field=models.ImageField(
                upload_to=app_remember.models.place_images_directory_path
            ),
        ),
        migrations.AlterField(
            model_name="images",
            name="place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="app_remember.place",
                verbose_name="photos",
            ),
        ),
    ]
