# Generated by Django 4.1.4 on 2023-03-04 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_remember", "0002_alter_images_images_alter_images_place"),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="app_remember.place",
                verbose_name="Photos",
            ),
        ),
    ]
