# Generated by Django 4.1.4 on 2023-01-03 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_user", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
